### ISSUE TITLE
workspace id treated as integer

### ISSUE THREAD

**Issue by rjake** [ryantsullivan/asanaR#1]
Happy to have found your `asanaR` package. When I run `get_workspaces()`, my id comes back as an integer and is unable to be passed to the `get_workspace()` function.

![image](https://user-images.githubusercontent.com/14003618/43283176-306136a4-90e6-11e8-9622-458affd6d9aa.png)

Can you have this read as a character instead?

Additionally, when I do pass the workspace id to the `get_workspace()` function, I get an error that the function `nest` from `tidyr` is not found.

**Comment by ryantsullivan** [comment]
Hey Jake! I never really ended up doing anything with this. I had planned to make an API wrapper but got distracted with other stuff at work. I have some time and could try to take it back up if there is interest.
